/**
 * Catalog invariants — the durable guard that keeps `data/models.json` a clean catalog
 * of real creators' canonical, normalized model ids (and overrides that always resolve).
 *
 * These are STRUCTURAL invariants enforced on every CI run. Both files are generated by
 * `scripts/generate-catalog.ts` (from the `src/creators/` + `src/providers/` registries); this test
 * catches the regressions a structural check can (underscores, casing, custom SKUs, broken refs).
 */
import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'

import { describe, expect, it } from 'vitest'

import { canonOf, isModelsDevRoutingAlias, prefixHit } from '../../scripts/canonicalize'
import { CREATORS } from '../creators'
import { isServerToolModelEligible } from '../patterns/serverToolModelEligibility'
import { PROVIDERS } from '../providers'
import { SERVER_TOOL } from '../schemas/enums'
import { ModelListSchema } from '../schemas/model'
import { ProviderListSchema } from '../schemas/provider'
import { ProviderModelListSchema } from '../schemas/provider-models'
import { ReasoningWireProfileSchema } from '../schemas/reasoningWire'
import { getServiceTierCatalogErrors } from '../utils/serviceTierCatalog'

const dataDir = join(fileURLToPath(import.meta.url), '..', '..', '..', 'data')
const modelsRaw = JSON.parse(readFileSync(join(dataDir, 'models.json'), 'utf8'))
const providerModelsRaw = JSON.parse(readFileSync(join(dataDir, 'provider-models.json'), 'utf8'))
const providersRaw = JSON.parse(readFileSync(join(dataDir, 'providers.json'), 'utf8'))
const models = modelsRaw.models as Array<{
  id: string
  name: string
  contextWindow?: number
  maxOutputTokens?: number
  capabilities?: string[]
  inputModalities?: string[]
  outputModalities?: string[]
  ownedBy?: string
  pricing?: {
    cacheRead?: { currency: string; perMillionTokens: number }
    input?: { currency: string; perMillionTokens: number }
    output?: { currency: string; perMillionTokens: number }
  }
  imageGeneration?: {
    modes?: {
      generate?: {
        supports?: {
          aspectRatio?: { default?: string; options?: string[]; render?: string; type?: string }
          imageResolution?: { default?: string; options?: string[]; render?: string; type?: string }
        }
      }
    }
  }
  reasoning?: {
    controls?: Array<{ kind: string; values?: string[] }>
  }
}>
const overrides = providerModelsRaw.overrides as Array<{
  providerId: string
  modelId: string
  apiModelId?: string
  name?: string
  pricing?: unknown
}>
const providers = ProviderListSchema.parse(providersRaw).providers
const providerModelOverrides = ProviderModelListSchema.parse(providerModelsRaw).overrides

// normalized creator id: lowercase, alphanumerics joined by single hyphens (size/version kept)
const NORMALIZED = /^[a-z0-9]+(?:-[a-z0-9]+)*$/
// shapes a creator never publishes: custom SKUs, double-dash vendor wrappers, routers
const JUNK = /(?:-vip|-ssvip|-cursor|-all|-nx|-gizmo|-mobile)$|--|^duo-chat-|\bauto\b/

const GEMINI_IMAGE_ASPECT_RATIO_OPTIONS = [
  {
    modelId: 'gemini-3-1-flash-image',
    options: [
      'auto',
      'ASPECT_1_1',
      'ASPECT_1_4',
      'ASPECT_1_8',
      'ASPECT_2_3',
      'ASPECT_3_2',
      'ASPECT_3_4',
      'ASPECT_4_1',
      'ASPECT_4_3',
      'ASPECT_4_5',
      'ASPECT_5_4',
      'ASPECT_8_1',
      'ASPECT_9_16',
      'ASPECT_16_9',
      'ASPECT_21_9'
    ]
  }
] as const

describe('catalog invariants (data/*.json)', () => {
  const ids = models.map((m) => m.id)
  const baseIds = new Set(ids)

  it.each([
    // OpenRouter renamed the vendor prefix (Microsoft → MicrosoftAI) in the same batch as MiniMax → MiniMaxAI.
    ['mai-image-2-5', 'microsoft', 'Microsoft AI: MAI-Image-2.5'],
    ['recraft-v4-1-vector', 'recraft', 'Recraft: Recraft V4.1 Vector'],
    ['riverflow-v2-5-fast', 'sourceful', 'Sourceful: Riverflow V2.5 Fast'],
    ['seedream-4-5', 'bytedance', 'Seedream 4.5']
  ])('catalogs OpenRouter image model %s under its creator with its display name', (modelId, ownedBy, name) => {
    expect(models.find((model) => model.id === modelId)).toMatchObject({
      capabilities: expect.arrayContaining(['image-generation']),
      name,
      ownedBy
    })
  })

  it.each(GEMINI_IMAGE_ASPECT_RATIO_OPTIONS)(
    'keeps smart aspect ratio and explicit resolution controls for $modelId',
    ({ modelId, options }) => {
      const supports = models.find((model) => model.id === modelId)?.imageGeneration?.modes?.generate?.supports

      expect(supports?.aspectRatio).toEqual({
        default: 'auto',
        options,
        render: 'chips',
        type: 'enum'
      })
      expect(supports?.imageResolution).toEqual({
        default: 'auto',
        options: ['auto', '1K', '2K', '4K'],
        render: 'chips',
        type: 'enum'
      })
    }
  )

  // `listProviderPresetModels` sends `apiModelId ?? modelId` on the wire, so a row whose canonical key
  // is not the served id must carry `apiModelId` — otherwise the canonical spelling (`glm-5-2` for
  // `glm-5.2`) goes out and 404s. Generation derives both from the authored id; this catches a row
  // that reached the catalog without passing through that split.
  it('every override either is keyed canonically or carries a wire id', () => {
    const leaking = overrides
      .filter((override) => !override.apiModelId && canonOf(override.modelId) !== override.modelId)
      .map((override) => `${override.providerId}/${override.modelId}`)
    expect(leaking).toEqual([])
  })

  it('Fireworks rows carry account-scoped wire ids', () => {
    const invalid = overrides
      .filter(({ providerId }) => providerId === 'fireworks')
      .filter(({ apiModelId }) => !apiModelId?.match(/^accounts\/fireworks\/(models|routers)\//))
      .map(({ modelId }) => modelId)

    expect(invalid).toEqual([])
  })

  it('base model ids are unique', () => {
    expect(ids.filter((id, i) => ids.indexOf(id) !== i)).toEqual([])
  })

  it('base models are sorted by creator and id', () => {
    const keys = models.map((model) => `${model.ownedBy ?? ''}\0${model.id}`)
    expect(keys).toEqual([...keys].sort())
  })

  it('every base id is a normalized creator id (lowercase, single-hyphen separated)', () => {
    expect(ids.filter((id) => !NORMALIZED.test(id))).toEqual([])
  })

  it('no junk id patterns (custom SKUs / vendor wrappers / routers)', () => {
    expect(ids.filter((id) => JUNK.test(id))).toEqual([])
  })

  // Canonicalization must be idempotent on the artifact itself: a base id the canonicalizer would
  // still fold (id !== canonOf(id)) means a variant/date row leaked through a non-fixpoint strip pass
  // and coexists with (or shadows) its true base row.
  it('every base id is a canonicalization fixpoint (id === canonOf(id))', () => {
    expect(ids.filter((id) => canonOf(id) !== id)).toEqual([])
  })

  // A `:batch` twin bills through OpenRouter's async job API, which the app never calls — it must not
  // reach the catalog as a model or as a provider row (see scripts/canonicalize.ts).
  it('excludes batch-API twins from both the catalog and provider rows', () => {
    const isBatch = (id: string) => /[:-]batch$/.test(id)
    expect([
      ...ids.filter(isBatch),
      ...overrides.filter((o) => isBatch(o.apiModelId ?? o.modelId)).map((o) => `${o.providerId}/${o.apiModelId}`)
    ]).toEqual([])
  })

  it('keeps the OpenRouter-only DeepSeek router alias out of the creator catalog', () => {
    const aliases = overrides.filter(
      (override) => override.providerId === 'openrouter' && override.apiModelId?.startsWith('~')
    )

    expect(aliases.length).toBeGreaterThan(0)
    const deepseekLatest = aliases.find((override) => override.apiModelId === '~deepseek/deepseek-v4-flash-latest')
    expect(deepseekLatest).toMatchObject({
      modelId: 'deepseek-v4-flash-latest',
      name: 'DeepSeek V4 Flash Latest'
    })
    expect(baseIds.has(deepseekLatest!.modelId)).toBe(false)
    expect(deepseekLatest?.pricing).toBeUndefined()
  })

  it('keeps the declared OpenRouter GPT image route out of the OpenAI creator catalog', () => {
    expect(PROVIDERS.find((provider) => provider.id === 'openrouter')?.standaloneModelIds).toEqual(['gpt-5-4-image-2'])
    expect(ids).not.toContain('gpt-5-4-image-2')
    expect(
      providerModelOverrides.find(
        (override) => override.providerId === 'openrouter' && override.apiModelId === 'openai/gpt-5.4-image-2'
      )
    ).toMatchObject({
      modelId: 'gpt-5-4-image-2',
      capabilities: { add: expect.arrayContaining(['image-generation']) },
      endpointTypes: expect.arrayContaining(['openai-image-generation']),
      name: 'OpenAI: GPT-5.4 Image 2',
      ownedBy: 'openrouter'
    })
  })

  it('drops Vercel OpenAI fast routing aliases without dropping real fast models', () => {
    expect(isModelsDevRoutingAlias('vercel', 'openai/gpt-5-fast')).toBe(true)
    expect(isModelsDevRoutingAlias('vercel', 'bytedance/seedance-2.0-fast')).toBe(false)
    expect(isModelsDevRoutingAlias('openrouter', 'anthropic/claude-opus-4.8-fast')).toBe(false)
    expect(models.some((model) => model.id === 'claude-opus-4-8-fast')).toBe(true)
    expect(
      models.filter((model) => model.ownedBy === 'openai' && model.id.endsWith('-fast')).map((model) => model.id)
    ).toEqual([])
    expect(
      overrides
        .filter((override) => override.providerId === 'gateway' && /^openai\/.+-fast$/.test(override.apiModelId ?? ''))
        .map((override) => override.apiModelId)
    ).toEqual([])
  })

  it('assigns overlapping creator prefixes to the most specific owner', () => {
    const wrongOwner = models
      .map((model) => {
        const mostSpecific = CREATORS.flatMap((creator) =>
          (creator.idPrefixes ?? [])
            .filter((prefix) => prefixHit(model.id, prefix))
            .map((prefix) => ({ creatorId: creator.id, prefix }))
        ).sort((a, b) => b.prefix.length - a.prefix.length)[0]
        return mostSpecific && mostSpecific.creatorId !== model.ownedBy
          ? `${model.id}: ${model.ownedBy} != ${mostSpecific.creatorId} (${mostSpecific.prefix})`
          : undefined
      })
      .filter(Boolean)
    expect(wrongOwner).toEqual([])
  })

  it('every override resolves to a base row or carries a standalone name', () => {
    const broken = overrides
      .filter((o) => !baseIds.has(o.modelId) && !o.name)
      .map((o) => `${o.providerId}/${o.modelId}`)
    expect(broken).toEqual([])
  })

  // OpenCode Go is one base URL over three wire protocols picked per model, and its served list comes
  // from models.dev — so a newly synced model lands here unpinned and silently falls back to
  // chat/completions (#17860). Classify it against models.dev's per-model `provider.npm`.
  it('pins an endpoint on every OpenCode Go model', () => {
    const unpinned = providerModelOverrides
      .filter((o) => o.providerId === 'opencode' && !o.endpointTypes?.length)
      .map((o) => o.modelId)
    expect(unpinned).toEqual([])
  })

  it('does not encode provider-native web search as a generic model capability', () => {
    expect(models.filter((model) => model.capabilities?.includes('web-search')).map((model) => model.id)).toEqual([])
  })

  // Image-generation models must not inherit web-search eligibility — it leaks a server tool onto image rows.
  // The sole exception is gemini-3 image (Nano Banana Pro), which genuinely grounds on Google Search;
  // every other image model (e.g. gemini-2.5-flash-image) must not carry it. The generator already strips
  // PREFIX-inherited web-search from image rows; this catches a HAND-LISTED `web-search` slipping back in.
  it('no image-generation model is web-search eligible except allowlisted gemini-3 image models', () => {
    const WEB_SEARCH_IMAGE_ALLOWLIST = new Set(['gemini-3-pro-image', 'gemini-3-pro-image-preview'])
    const offenders = models
      .filter((model) => model.capabilities?.includes('image-generation'))
      .filter((model) =>
        providers.some((provider) => isServerToolModelEligible(model.id, provider.id, SERVER_TOOL.WEB_SEARCH))
      )
      .map((model) => model.id)
      .filter((id) => !WEB_SEARCH_IMAGE_ALLOWLIST.has(id))
    expect(offenders).toEqual([])
  })

  // Web search is a text-chat server tool: a model that doesn't converse in text on both sides (TTS is
  // text→audio, transcription is audio→text, embedders output vector) must never be eligible.
  it('no non-text-chat model is web-search eligible (tts / transcription / embedding)', () => {
    const offenders = models
      .filter((model) =>
        providers.some((provider) => isServerToolModelEligible(model.id, provider.id, SERVER_TOOL.WEB_SEARCH))
      )
      .filter(
        (m) => !(m.inputModalities ?? ['text']).includes('text') || !(m.outputModalities ?? ['text']).includes('text')
      )
      .map((m) => m.id)
    expect(offenders).toEqual([])
  })

  // The loader's canonical override index (`overrideByKey`) resolves a duplicated key to the self
  // variant (`apiModelId === modelId`) — see registry-loader.ts `buildOverrideIndex`. A duplicated key
  // with NO self variant makes the winning override file-order-dependent, so forbid it.
  it('every duplicated providerId::modelId key contains a self variant', () => {
    const byKey = new Map<string, Array<(typeof overrides)[number]>>()
    for (const o of overrides) {
      const key = `${o.providerId}::${o.modelId}`
      byKey.set(key, [...(byKey.get(key) ?? []), o])
    }
    const orderDependent = [...byKey.entries()]
      .filter(([, rows]) => rows.length > 1 && !rows.some((r) => (r.apiModelId ?? r.modelId) === r.modelId))
      .map(([key]) => key)
    expect(orderDependent).toEqual([])
  })

  // `[1m]` is a Claude Code CLI suffix that raises the session's context budget: it never reaches an
  // API, so it may only appear as an apiModelId, only on that provider, only paired with the plain
  // row users pick when they don't want the extended window, and only on a model that has 1M to give.
  it('every [1m] apiModelId is a claude-code twin of a plain 1M-context row', () => {
    const contextWindowById = new Map(models.map((m) => [m.id, m.contextWindow]))
    const plainRows = new Set(
      overrides.filter((o) => (o.apiModelId ?? o.modelId) === o.modelId).map((o) => `${o.providerId}::${o.modelId}`)
    )
    const broken = overrides
      .filter((o) => (o.apiModelId ?? '').endsWith('[1m]'))
      .filter(
        (o) =>
          o.providerId !== 'claude-code' ||
          o.apiModelId !== `${o.modelId}[1m]` ||
          !plainRows.has(`${o.providerId}::${o.modelId}`) ||
          (contextWindowById.get(o.modelId) ?? 0) < 1_000_000
      )
      .map((o) => `${o.providerId}/${o.apiModelId}`)
    expect(broken).toEqual([])
  })

  // sequentialImageGeneration is a string enum in the central catalog
  // (imageParamCatalog.ts) and the Doubao API only accepts 'auto'/'disabled' — a
  // `switch` support spec here renders a boolean UI control that gets coerced
  // away before the request, silently no-opping the feature (aihubmix's
  // doubao-seedream-4-0/4-5 had this; dmxapi's doubao model already declares it
  // correctly as the reference shape).
  it('sequentialImageGeneration is never declared as a switch (must be the string enum)', () => {
    type Row = { id?: string; modelId?: string; providerId?: string; imageGeneration?: unknown }
    const allRows: Row[] = [...(modelsRaw.models as Row[]), ...(providerModelsRaw.overrides as Row[])]
    const offenders: string[] = []
    for (const row of allRows) {
      const modes = (row.imageGeneration as { modes?: Record<string, unknown> } | undefined)?.modes ?? {}
      for (const [modeName, def] of Object.entries(modes)) {
        const spec = (def as { supports?: Record<string, { type?: string }> }).supports?.sequentialImageGeneration
        if (spec?.type === 'switch') {
          offenders.push(`${row.providerId ?? 'base'}/${row.modelId ?? row.id}:${modeName}`)
        }
      }
    }
    expect(offenders).toEqual([])
  })

  it('maxOutputTokens never exceeds contextWindow', () => {
    const bad = models.filter((m) => m.contextWindow && m.maxOutputTokens && m.maxOutputTokens > m.contextWindow)
    expect(bad.map((m) => m.id)).toEqual([])
  })

  it.each(['deepseek-v4-flash', 'deepseek-v4-pro'])('keeps the official DeepSeek V4 token limits for %s', (id) => {
    expect(models.find((model) => model.id === id)).toMatchObject({
      contextWindow: 1048576,
      maxOutputTokens: 393216
    })
  })

  it.each(['deepseek-v4-flash', 'deepseek-v4-flash-vision-exp', 'deepseek-v4-pro'])(
    'advertises only the official DeepSeek V4 reasoning efforts for %s',
    (id) => {
      expect(models.find((model) => model.id === id)?.reasoning?.controls).toEqual([
        { kind: 'effort', values: ['none', 'low', 'high', 'max'] }
      ])
    }
  )

  it('keeps DeepSeek V4 base pricing at the documented static peak ceiling', () => {
    const pricing = (id: string) => models.find((model) => model.id === id)?.pricing

    expect(pricing('deepseek-v4-flash')).toEqual({
      cacheRead: { currency: 'USD', perMillionTokens: 0.014 },
      input: { currency: 'USD', perMillionTokens: 0.44 },
      output: { currency: 'USD', perMillionTokens: 1.32 }
    })
    expect(pricing('deepseek-v4-flash-vision-exp')).toEqual(pricing('deepseek-v4-flash'))
    expect(pricing('deepseek-v4-pro')).toEqual({
      cacheRead: { currency: 'USD', perMillionTokens: 0.044 },
      input: { currency: 'USD', perMillionTokens: 1.32 },
      output: { currency: 'USD', perMillionTokens: 3.96 }
    })
    expect(pricing('deepseek-v4-flash-latest')).toBeUndefined()
  })

  // The list schemas drop entries they cannot parse (forward compatibility), so conformance
  // means BOTH "parses" and "nothing was silently dropped" — otherwise a broken bundled entry
  // would vanish from the shipped catalog without failing anything.
  it('models.json conforms to ModelListSchema with no entry dropped', () => {
    const r = ModelListSchema.safeParse(modelsRaw)
    expect(r.success ? [] : r.error.issues.slice(0, 5)).toEqual([])
    expect(r.success && r.data.models.length).toBe(modelsRaw.models.length)
  })

  it('provider-models.json conforms to ProviderModelListSchema with no entry dropped', () => {
    const r = ProviderModelListSchema.safeParse(providerModelsRaw)
    expect(r.success ? [] : r.error.issues.slice(0, 5)).toEqual([])
    expect(r.success && r.data.overrides.length).toBe(providerModelsRaw.overrides.length)
  })

  it('Fast transports belong only to Codex, Claude Code, and Ark', () => {
    expect(
      providers
        .filter((provider) => provider.fastMode)
        .map((provider) => provider.id)
        .sort()
    ).toEqual(['claude-code', 'doubao', 'openai-codex'])
  })

  it('Fast provider-model declarations require a provider transport', () => {
    const fastProviders = new Set(providers.filter((provider) => provider.fastMode).map((provider) => provider.id))
    expect(
      providerModelOverrides
        .filter((override) => override.supportsFastMode && !fastProviders.has(override.providerId))
        .map((override) => `${override.providerId}/${override.modelId}`)
    ).toEqual([])
  })

  it('service tier overrides only expose options mapped by their endpoints', () => {
    expect(getServiceTierCatalogErrors(providers, providerModelOverrides)).toEqual([])
  })

  it('budget wire operations require an explicit budget policy', () => {
    const result = ReasoningWireProfileSchema.safeParse({
      effort: {
        operations: [{ target: 'thinking_budget', value: { source: 'budget' } }]
      }
    })
    expect(result.success).toBe(false)
  })

  it('the validators actually reject known-bad shapes', () => {
    expect(NORMALIZED.test('GLM-4_5')).toBe(false) // uppercase + underscore
    expect(NORMALIZED.test('anthropic--claude-3-5-sonnet')).toBe(false) // double-dash
    expect(NORMALIZED.test('claude-3-5-sonnet@20240620')).toBe(false) // @date
    expect(JUNK.test('gpt-4o-image-vip')).toBe(true)
    expect(JUNK.test('duo-chat-gpt-5-2')).toBe(true)
    expect(JUNK.test('claude-3-5-sonnet')).toBe(false) // real id must pass
  })
})
